#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IdoMaster_GensouWorld.Resource", IsApplication=true)]

namespace IdoMaster_GensouWorld
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int anime_breathe = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int anime_shake = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int anime_video_wait = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int create_zoomin = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int create_zoomout = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int dialog_fade_in = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int dialog_fade_out = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int drop_down_from_top = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int drop_down_to_bottom = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int fade_in_center = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int fade_out_center = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int finish_zoomin = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int finish_zoomout = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int grow_fade_in_from_bottom = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hide_to_top = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int list_item_zoom_in = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int list_item_zoom_out = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int popup_form_bottom = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int screen_shake_anim = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int shake_cycle = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int shake_item = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int shrink_fade_out_from_bottom = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int slide_in_bottom = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int slide_out_bottom = 2131034135;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010024
			public const int color_finger_on = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int color_finger_up = 2130772005;
			
			// aapt resource value: 0x7f010022
			public const int color_no_finger_inner_circle = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int color_no_finger_outer_circle = 2130772003;
			
			// aapt resource value: 0x7f010026
			public const int count = 2130772006;
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f01001a
			public const int font = 2130771994;
			
			// aapt resource value: 0x7f010013
			public const int fontProviderAuthority = 2130771987;
			
			// aapt resource value: 0x7f010016
			public const int fontProviderCerts = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int fontProviderFetchStrategy = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int fontProviderFetchTimeout = 2130771992;
			
			// aapt resource value: 0x7f010014
			public const int fontProviderPackage = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int fontProviderQuery = 2130771989;
			
			// aapt resource value: 0x7f010019
			public const int fontStyle = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int fontWeight = 2130771995;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010012
			public const int layout_aspectRatio = 2130771986;
			
			// aapt resource value: 0x7f01000a
			public const int layout_heightPercent = 2130771978;
			
			// aapt resource value: 0x7f01000f
			public const int layout_marginBottomPercent = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int layout_marginEndPercent = 2130771985;
			
			// aapt resource value: 0x7f01000c
			public const int layout_marginLeftPercent = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int layout_marginPercent = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int layout_marginRightPercent = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int layout_marginStartPercent = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int layout_marginTopPercent = 2130771981;
			
			// aapt resource value: 0x7f010009
			public const int layout_widthPercent = 2130771977;
			
			// aapt resource value: 0x7f010028
			public const int maxHeight = 2130772008;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f01001e
			public const int textColor = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int textContent = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int textSize = 2130771997;
			
			// aapt resource value: 0x7f010020
			public const int textSpacingAdd = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int textSpacingMult = 2130771999;
			
			// aapt resource value: 0x7f010021
			public const int textXAlignment = 2130772001;
			
			// aapt resource value: 0x7f010027
			public const int tryTimes = 2130772007;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0e0000
			public const int abc_action_bar_embed_tabs = 2131623936;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0b0014
			public const int Grey_100 = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int Grey_200 = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int Grey_300 = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int Grey_400 = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int Grey_50 = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int Grey_500 = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int Grey_600 = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int Grey_700 = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int Grey_800 = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int Grey_900 = 2131427357;
			
			// aapt resource value: 0x7f0b0053
			public const int aliceblue = 2131427411;
			
			// aapt resource value: 0x7f0b0048
			public const int antiquewhite = 2131427400;
			
			// aapt resource value: 0x7f0b00a9
			public const int aqua = 2131427497;
			
			// aapt resource value: 0x7f0b008a
			public const int aquamarine = 2131427466;
			
			// aapt resource value: 0x7f0b0051
			public const int azure = 2131427409;
			
			// aapt resource value: 0x7f0b004e
			public const int beige = 2131427406;
			
			// aapt resource value: 0x7f0b0007
			public const int bgColor_actionsheet_cancel_nor = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int bgColor_alert_button_press = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int bgColor_alertview_alert = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int bgColor_alertview_alert_start = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int bgColor_divier = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int bgColor_overlay = 2131427340;
			
			// aapt resource value: 0x7f0b0031
			public const int bisque = 2131427377;
			
			// aapt resource value: 0x7f0b00b8
			public const int black = 2131427512;
			
			// aapt resource value: 0x7f0b002f
			public const int blanchedalmond = 2131427375;
			
			// aapt resource value: 0x7f0b00b4
			public const int blue = 2131427508;
			
			// aapt resource value: 0x7f0b0082
			public const int blueviolet = 2131427458;
			
			// aapt resource value: 0x7f0b0077
			public const int brown = 2131427447;
			
			// aapt resource value: 0x7f0b005b
			public const int burlywood = 2131427419;
			
			// aapt resource value: 0x7f0b0098
			public const int cadetblue = 2131427480;
			
			// aapt resource value: 0x7f0b008b
			public const int chartreuse = 2131427467;
			
			// aapt resource value: 0x7f0b0066
			public const int chocolate = 2131427430;
			
			// aapt resource value: 0x7f0b0022
			public const int colorAccent = 2131427362;
			
			// aapt resource value: 0x7f0b0020
			public const int colorPrimary = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int colorPrimaryDark = 2131427361;
			
			// aapt resource value: 0x7f0b003d
			public const int coral = 2131427389;
			
			// aapt resource value: 0x7f0b0097
			public const int cornflowerblue = 2131427479;
			
			// aapt resource value: 0x7f0b002b
			public const int cornsilk = 2131427371;
			
			// aapt resource value: 0x7f0b005e
			public const int crimson = 2131427422;
			
			// aapt resource value: 0x7f0b00aa
			public const int cyan = 2131427498;
			
			// aapt resource value: 0x7f0b00b6
			public const int darkblue = 2131427510;
			
			// aapt resource value: 0x7f0b00b0
			public const int darkcyan = 2131427504;
			
			// aapt resource value: 0x7f0b006e
			public const int darkgoldenrod = 2131427438;
			
			// aapt resource value: 0x7f0b0075
			public const int darkgray = 2131427445;
			
			// aapt resource value: 0x7f0b00b3
			public const int darkgreen = 2131427507;
			
			// aapt resource value: 0x7f0b0076
			public const int darkgrey = 2131427446;
			
			// aapt resource value: 0x7f0b006b
			public const int darkkhaki = 2131427435;
			
			// aapt resource value: 0x7f0b0080
			public const int darkmagenta = 2131427456;
			
			// aapt resource value: 0x7f0b0099
			public const int darkolivegreen = 2131427481;
			
			// aapt resource value: 0x7f0b003c
			public const int darkorange = 2131427388;
			
			// aapt resource value: 0x7f0b0079
			public const int darkorchid = 2131427449;
			
			// aapt resource value: 0x7f0b0081
			public const int darkred = 2131427457;
			
			// aapt resource value: 0x7f0b0058
			public const int darksalmon = 2131427416;
			
			// aapt resource value: 0x7f0b007e
			public const int darkseagreen = 2131427454;
			
			// aapt resource value: 0x7f0b009c
			public const int darkslateblue = 2131427484;
			
			// aapt resource value: 0x7f0b00a2
			public const int darkslategray = 2131427490;
			
			// aapt resource value: 0x7f0b00a3
			public const int darkslategrey = 2131427491;
			
			// aapt resource value: 0x7f0b00ae
			public const int darkturquoise = 2131427502;
			
			// aapt resource value: 0x7f0b007b
			public const int darkviolet = 2131427451;
			
			// aapt resource value: 0x7f0b0041
			public const int deeppink = 2131427393;
			
			// aapt resource value: 0x7f0b00af
			public const int deepskyblue = 2131427503;
			
			// aapt resource value: 0x7f0b0094
			public const int dimgray = 2131427476;
			
			// aapt resource value: 0x7f0b0095
			public const int dimgrey = 2131427477;
			
			// aapt resource value: 0x7f0b00a7
			public const int dodgerblue = 2131427495;
			
			// aapt resource value: 0x7f0b006f
			public const int firebrick = 2131427439;
			
			// aapt resource value: 0x7f0b0029
			public const int floralwhite = 2131427369;
			
			// aapt resource value: 0x7f0b00a5
			public const int forestgreen = 2131427493;
			
			// aapt resource value: 0x7f0b0042
			public const int fuchsia = 2131427394;
			
			// aapt resource value: 0x7f0b005d
			public const int gainsboro = 2131427421;
			
			// aapt resource value: 0x7f0b004a
			public const int ghostwhite = 2131427402;
			
			// aapt resource value: 0x7f0b004b
			public const int ghostwhite_toast = 2131427403;
			
			// aapt resource value: 0x7f0b0035
			public const int gold = 2131427381;
			
			// aapt resource value: 0x7f0b0060
			public const int goldenrod = 2131427424;
			
			// aapt resource value: 0x7f0b0085
			public const int gray = 2131427461;
			
			// aapt resource value: 0x7f0b00b2
			public const int green = 2131427506;
			
			// aapt resource value: 0x7f0b0073
			public const int greenyellow = 2131427443;
			
			// aapt resource value: 0x7f0b0086
			public const int grey = 2131427462;
			
			// aapt resource value: 0x7f0b0052
			public const int honeydew = 2131427410;
			
			// aapt resource value: 0x7f0b003e
			public const int hotpink = 2131427390;
			
			// aapt resource value: 0x7f0b0068
			public const int indianred = 2131427432;
			
			// aapt resource value: 0x7f0b009a
			public const int indigo = 2131427482;
			
			// aapt resource value: 0x7f0b0025
			public const int ivory = 2131427365;
			
			// aapt resource value: 0x7f0b0054
			public const int khaki = 2131427412;
			
			// aapt resource value: 0x7f0b0023
			public const int kuuhaku = 2131427363;
			
			// aapt resource value: 0x7f0b0059
			public const int lavender = 2131427417;
			
			// aapt resource value: 0x7f0b002d
			public const int lavenderblush = 2131427373;
			
			// aapt resource value: 0x7f0b008c
			public const int lawngreen = 2131427468;
			
			// aapt resource value: 0x7f0b002a
			public const int lemonchiffon = 2131427370;
			
			// aapt resource value: 0x7f0b0074
			public const int lightblue = 2131427444;
			
			// aapt resource value: 0x7f0b0055
			public const int lightcoral = 2131427413;
			
			// aapt resource value: 0x7f0b005a
			public const int lightcyan = 2131427418;
			
			// aapt resource value: 0x7f0b0046
			public const int lightgoldenrodyellow = 2131427398;
			
			// aapt resource value: 0x7f0b0063
			public const int lightgray = 2131427427;
			
			// aapt resource value: 0x7f0b007d
			public const int lightgreen = 2131427453;
			
			// aapt resource value: 0x7f0b0064
			public const int lightgrey = 2131427428;
			
			// aapt resource value: 0x7f0b0039
			public const int lightpink = 2131427385;
			
			// aapt resource value: 0x7f0b003b
			public const int lightsalmon = 2131427387;
			
			// aapt resource value: 0x7f0b00a6
			public const int lightseagreen = 2131427494;
			
			// aapt resource value: 0x7f0b0083
			public const int lightskyblue = 2131427459;
			
			// aapt resource value: 0x7f0b008e
			public const int lightslategray = 2131427470;
			
			// aapt resource value: 0x7f0b008f
			public const int lightslategrey = 2131427471;
			
			// aapt resource value: 0x7f0b0071
			public const int lightsteelblue = 2131427441;
			
			// aapt resource value: 0x7f0b0026
			public const int lightyellow = 2131427366;
			
			// aapt resource value: 0x7f0b00ac
			public const int lime = 2131427500;
			
			// aapt resource value: 0x7f0b00a1
			public const int limegreen = 2131427489;
			
			// aapt resource value: 0x7f0b0047
			public const int linen = 2131427399;
			
			// aapt resource value: 0x7f0b0043
			public const int magenta = 2131427395;
			
			// aapt resource value: 0x7f0b0089
			public const int maroon = 2131427465;
			
			// aapt resource value: 0x7f0b0096
			public const int mediumaquamarine = 2131427478;
			
			// aapt resource value: 0x7f0b00b5
			public const int mediumblue = 2131427509;
			
			// aapt resource value: 0x7f0b006d
			public const int mediumorchid = 2131427437;
			
			// aapt resource value: 0x7f0b007c
			public const int mediumpurple = 2131427452;
			
			// aapt resource value: 0x7f0b00a0
			public const int mediumseagreen = 2131427488;
			
			// aapt resource value: 0x7f0b008d
			public const int mediumslateblue = 2131427469;
			
			// aapt resource value: 0x7f0b00ad
			public const int mediumspringgreen = 2131427501;
			
			// aapt resource value: 0x7f0b009b
			public const int mediumturquoise = 2131427483;
			
			// aapt resource value: 0x7f0b0069
			public const int mediumvioletred = 2131427433;
			
			// aapt resource value: 0x7f0b00a8
			public const int midnightblue = 2131427496;
			
			// aapt resource value: 0x7f0b004c
			public const int mintcream = 2131427404;
			
			// aapt resource value: 0x7f0b0030
			public const int mistyrose = 2131427376;
			
			// aapt resource value: 0x7f0b0032
			public const int moccasin = 2131427378;
			
			// aapt resource value: 0x7f0b0033
			public const int navajowhite = 2131427379;
			
			// aapt resource value: 0x7f0b00b7
			public const int navy = 2131427511;
			
			// aapt resource value: 0x7f0b0003
			public const int notification_action_color_filter = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int notification_icon_bg_color = 2131427332;
			
			// aapt resource value: 0x7f0b0000
			public const int notification_material_background_media_default_color = 2131427328;
			
			// aapt resource value: 0x7f0b0045
			public const int oldlace = 2131427397;
			
			// aapt resource value: 0x7f0b0087
			public const int olive = 2131427463;
			
			// aapt resource value: 0x7f0b0092
			public const int olivedrab = 2131427474;
			
			// aapt resource value: 0x7f0b003a
			public const int orange = 2131427386;
			
			// aapt resource value: 0x7f0b0040
			public const int orangered = 2131427392;
			
			// aapt resource value: 0x7f0b0061
			public const int orchid = 2131427425;
			
			// aapt resource value: 0x7f0b0056
			public const int palegoldenrod = 2131427414;
			
			// aapt resource value: 0x7f0b007a
			public const int palegreen = 2131427450;
			
			// aapt resource value: 0x7f0b0072
			public const int paleturquoise = 2131427442;
			
			// aapt resource value: 0x7f0b005f
			public const int palevioletred = 2131427423;
			
			// aapt resource value: 0x7f0b002e
			public const int papayawhip = 2131427374;
			
			// aapt resource value: 0x7f0b0034
			public const int peachpuff = 2131427380;
			
			// aapt resource value: 0x7f0b0067
			public const int peru = 2131427431;
			
			// aapt resource value: 0x7f0b0036
			public const int pink = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int pink_trans = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int pink_trans_toast = 2131427384;
			
			// aapt resource value: 0x7f0b005c
			public const int plum = 2131427420;
			
			// aapt resource value: 0x7f0b0070
			public const int powderblue = 2131427440;
			
			// aapt resource value: 0x7f0b0001
			public const int primary_text_default_material_dark = 2131427329;
			
			// aapt resource value: 0x7f0b0088
			public const int purple = 2131427464;
			
			// aapt resource value: 0x7f0b0044
			public const int red = 2131427396;
			
			// aapt resource value: 0x7f0b0005
			public const int ripple_material_light = 2131427333;
			
			// aapt resource value: 0x7f0b006c
			public const int rosybrown = 2131427436;
			
			// aapt resource value: 0x7f0b009e
			public const int royalblue = 2131427486;
			
			// aapt resource value: 0x7f0b007f
			public const int saddlebrown = 2131427455;
			
			// aapt resource value: 0x7f0b0049
			public const int salmon = 2131427401;
			
			// aapt resource value: 0x7f0b0050
			public const int sandybrown = 2131427408;
			
			// aapt resource value: 0x7f0b002c
			public const int seaShell = 2131427372;
			
			// aapt resource value: 0x7f0b00a4
			public const int seagreen = 2131427492;
			
			// aapt resource value: 0x7f0b0002
			public const int secondary_text_default_material_dark = 2131427330;
			
			// aapt resource value: 0x7f0b0006
			public const int secondary_text_default_material_light = 2131427334;
			
			// aapt resource value: 0x7f0b0078
			public const int sienna = 2131427448;
			
			// aapt resource value: 0x7f0b006a
			public const int silver = 2131427434;
			
			// aapt resource value: 0x7f0b001e
			public const int simple_player_stream_name_normal = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int simple_player_stream_name_playing = 2131427359;
			
			// aapt resource value: 0x7f0b0084
			public const int skyblue = 2131427460;
			
			// aapt resource value: 0x7f0b0093
			public const int slateblue = 2131427475;
			
			// aapt resource value: 0x7f0b0090
			public const int slategray = 2131427472;
			
			// aapt resource value: 0x7f0b0091
			public const int slategrey = 2131427473;
			
			// aapt resource value: 0x7f0b0028
			public const int snow = 2131427368;
			
			// aapt resource value: 0x7f0b00ab
			public const int springgreen = 2131427499;
			
			// aapt resource value: 0x7f0b009d
			public const int steelblue = 2131427485;
			
			// aapt resource value: 0x7f0b0065
			public const int tan = 2131427429;
			
			// aapt resource value: 0x7f0b00b1
			public const int teal = 2131427505;
			
			// aapt resource value: 0x7f0b000d
			public const int textColor_actionsheet_msg = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int textColor_actionsheet_title = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int textColor_alert_button_cancel = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int textColor_alert_button_destructive = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int textColor_alert_button_others = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int textColor_alert_msg = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int textColor_alert_title = 2131427347;
			
			// aapt resource value: 0x7f0b0062
			public const int thistle = 2131427426;
			
			// aapt resource value: 0x7f0b003f
			public const int tomato = 2131427391;
			
			// aapt resource value: 0x7f0b009f
			public const int turquoise = 2131427487;
			
			// aapt resource value: 0x7f0b0057
			public const int violet = 2131427415;
			
			// aapt resource value: 0x7f0b004f
			public const int wheat = 2131427407;
			
			// aapt resource value: 0x7f0b0024
			public const int white = 2131427364;
			
			// aapt resource value: 0x7f0b004d
			public const int whitesmoke = 2131427405;
			
			// aapt resource value: 0x7f0b0027
			public const int yellow = 2131427367;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080028
			public const int activity_horizontal_margin = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int activity_vertical_margin = 2131230761;
			
			// aapt resource value: 0x7f08000a
			public const int compat_button_inset_horizontal_material = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int compat_button_inset_vertical_material = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int compat_button_padding_horizontal_material = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int compat_button_padding_vertical_material = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int compat_control_corner_material = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int fastscroll_default_thickness = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int fastscroll_margin = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int fastscroll_minimum_range = 2131230722;
			
			// aapt resource value: 0x7f08001a
			public const int height_actionsheet_title = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int height_alert_button = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int height_alert_title = 2131230748;
			
			// aapt resource value: 0x7f080003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int item_touch_helper_swipe_escape_velocity = 2131230725;
			
			// aapt resource value: 0x7f08001d
			public const int marginBottom_actionsheet_msg = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int marginBottom_alert_msg = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int margin_actionsheet_left_right = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int margin_alert_left_right = 2131230752;
			
			// aapt resource value: 0x7f08002a
			public const int media_player_height = 2131230762;
			
			// aapt resource value: 0x7f08000f
			public const int notification_action_icon_size = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int notification_action_text_size = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int notification_big_circle_margin = 2131230737;
			
			// aapt resource value: 0x7f080007
			public const int notification_content_margin_start = 2131230727;
			
			// aapt resource value: 0x7f080012
			public const int notification_large_icon_height = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int notification_large_icon_width = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int notification_main_column_padding_top = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int notification_media_narrow_margin = 2131230729;
			
			// aapt resource value: 0x7f080014
			public const int notification_right_icon_size = 2131230740;
			
			// aapt resource value: 0x7f080006
			public const int notification_right_side_padding_top = 2131230726;
			
			// aapt resource value: 0x7f080015
			public const int notification_small_icon_background_padding = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int notification_small_icon_size_as_large = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int notification_subtext_size = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int notification_top_pad = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int notification_top_pad_large_text = 2131230745;
			
			// aapt resource value: 0x7f080021
			public const int radius_alertview = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int size_divier = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int textSize_actionsheet_msg = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int textSize_actionsheet_title = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int textSize_alert_button = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int textSize_alert_msg = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int textSize_alert_title = 2131230759;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_actionsheet_cancel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_actionsheet_header = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_alertbutton_bottom = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_alertbutton_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_alertbutton_none = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_alertbutton_right = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_alertview_alert = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_box_skill_introduce = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_box_talking = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_button_baltte_menu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_button_gacha = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_button_login = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg_button_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bg_char_equip = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bg_char_skill = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bg_check_battle_info = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bg_dividing_line = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bg_diy_dialog = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bg_diy_toast = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bg_edittext_login = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bg_edittext_login_error = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bg_film_diy_seekbar = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bg_film_episodes_select = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bg_gradient_home = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bg_history_selector = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bg_item_illustrate = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bg_pop_input = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bg_selector_chose_soubi_item = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bg_selector_room = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bg_selector_skill_or_item = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bg_selector_skills = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bg_shop_divier = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int bg_shop_tab = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int bg_skills_menu_total = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int cursor_default = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int diy_exp_progressbar = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int diy_exp_progressbar_for_char = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int diy_hp_progressbar_monster = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int list_item_zoom_in = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int list_item_zoom_out = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int notification_action_background = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int notification_bg = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int notification_bg_low = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int notification_bg_low_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int notification_bg_low_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int notification_bg_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int notification_bg_normal_pressed = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int notification_icon_background = 2130837551;
			
			// aapt resource value: 0x7f020054
			public const int notification_template_icon_bg = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int notification_template_icon_low_bg = 2130837589;
			
			// aapt resource value: 0x7f020030
			public const int notification_tile_bg = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int notify_panel_notification_icon_bg = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int qcloud_player_icon_audio_vol = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int qcloud_player_icon_audio_vol_mute = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int qcloud_player_icon_brightness = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int selector_film_episodes_item = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int selector_media_play_button = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int simple_player_arrow_white_24dp = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int simple_player_bg_normal = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int simple_player_bg_pressed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int simple_player_brightness_6_white_36dp = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int simple_player_btn = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int simple_player_center_bg = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int simple_player_center_pause = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int simple_player_center_play = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int simple_player_chevron_left_white_36dp = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int simple_player_circle_outline_white_36dp = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int simple_player_control_disabled_holo = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int simple_player_control_focused_holo = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int simple_player_control_normal_holo = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int simple_player_control_pressed_holo = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int simple_player_control_selector_holo_dark = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int simple_player_icon_fullscreen_shrink = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int simple_player_icon_fullscreen_stretch = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int simple_player_icon_media_pause = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int simple_player_iv_rotation = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int simple_player_menu = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int simple_player_primary_holo = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int simple_player_progress_horizontal_holo_dark = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int simple_player_secondary_holo = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int simple_player_stop_white_24dp = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int simple_player_track_holo_dark = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int simple_player_volume_off_white_36dp = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int simple_player_volume_up_white_36dp = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int textbg_open_intro = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int textbg_retry = 2130837587;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090090
			public const int action0 = 2131296400;
			
			// aapt resource value: 0x7f09008d
			public const int action_container = 2131296397;
			
			// aapt resource value: 0x7f090094
			public const int action_divider = 2131296404;
			
			// aapt resource value: 0x7f09008e
			public const int action_image = 2131296398;
			
			// aapt resource value: 0x7f09008f
			public const int action_text = 2131296399;
			
			// aapt resource value: 0x7f09009e
			public const int actions = 2131296414;
			
			// aapt resource value: 0x7f090088
			public const int alertButtonListView = 2131296392;
			
			// aapt resource value: 0x7f0900cc
			public const int app_video_box = 2131296460;
			
			// aapt resource value: 0x7f0900c6
			public const int app_video_brightness = 2131296454;
			
			// aapt resource value: 0x7f0900c4
			public const int app_video_brightness_box = 2131296452;
			
			// aapt resource value: 0x7f0900c5
			public const int app_video_brightness_icon = 2131296453;
			
			// aapt resource value: 0x7f0900b4
			public const int app_video_center = 2131296436;
			
			// aapt resource value: 0x7f0900c0
			public const int app_video_center_box = 2131296448;
			
			// aapt resource value: 0x7f0900b5
			public const int app_video_currentTime = 2131296437;
			
			// aapt resource value: 0x7f0900af
			public const int app_video_currentTime_full = 2131296431;
			
			// aapt resource value: 0x7f0900b1
			public const int app_video_currentTime_left = 2131296433;
			
			// aapt resource value: 0x7f0900b6
			public const int app_video_endTime = 2131296438;
			
			// aapt resource value: 0x7f0900b7
			public const int app_video_endTime_full = 2131296439;
			
			// aapt resource value: 0x7f0900b2
			public const int app_video_endTime_left = 2131296434;
			
			// aapt resource value: 0x7f0900c9
			public const int app_video_fastForward = 2131296457;
			
			// aapt resource value: 0x7f0900cb
			public const int app_video_fastForward_all = 2131296459;
			
			// aapt resource value: 0x7f0900c8
			public const int app_video_fastForward_box = 2131296456;
			
			// aapt resource value: 0x7f0900ca
			public const int app_video_fastForward_target = 2131296458;
			
			// aapt resource value: 0x7f0900bd
			public const int app_video_finish = 2131296445;
			
			// aapt resource value: 0x7f0900d5
			public const int app_video_freeTie = 2131296469;
			
			// aapt resource value: 0x7f0900d6
			public const int app_video_freeTie_icon = 2131296470;
			
			// aapt resource value: 0x7f0900ba
			public const int app_video_fullscreen = 2131296442;
			
			// aapt resource value: 0x7f0900b0
			public const int app_video_lift = 2131296432;
			
			// aapt resource value: 0x7f0900d7
			public const int app_video_loading = 2131296471;
			
			// aapt resource value: 0x7f0900bf
			public const int app_video_menu = 2131296447;
			
			// aapt resource value: 0x7f0900d3
			public const int app_video_netTie = 2131296467;
			
			// aapt resource value: 0x7f0900d4
			public const int app_video_netTie_icon = 2131296468;
			
			// aapt resource value: 0x7f0900ad
			public const int app_video_play = 2131296429;
			
			// aapt resource value: 0x7f0900ae
			public const int app_video_process_panl = 2131296430;
			
			// aapt resource value: 0x7f0900d0
			public const int app_video_replay = 2131296464;
			
			// aapt resource value: 0x7f0900d2
			public const int app_video_replay_icon = 2131296466;
			
			// aapt resource value: 0x7f0900b3
			public const int app_video_seekBar = 2131296435;
			
			// aapt resource value: 0x7f0900d8
			public const int app_video_speed = 2131296472;
			
			// aapt resource value: 0x7f0900d1
			public const int app_video_status_text = 2131296465;
			
			// aapt resource value: 0x7f0900b8
			public const int app_video_stream = 2131296440;
			
			// aapt resource value: 0x7f0900be
			public const int app_video_title = 2131296446;
			
			// aapt resource value: 0x7f0900bc
			public const int app_video_top_box = 2131296444;
			
			// aapt resource value: 0x7f0900c3
			public const int app_video_volume = 2131296451;
			
			// aapt resource value: 0x7f0900c1
			public const int app_video_volume_box = 2131296449;
			
			// aapt resource value: 0x7f0900c2
			public const int app_video_volume_icon = 2131296450;
			
			// aapt resource value: 0x7f090006
			public const int async = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int blocking = 2131296263;
			
			// aapt resource value: 0x7f090019
			public const int bt_attack = 2131296281;
			
			// aapt resource value: 0x7f09004a
			public const int bt_back = 2131296330;
			
			// aapt resource value: 0x7f09000b
			public const int bt_bankcard = 2131296267;
			
			// aapt resource value: 0x7f090048
			public const int bt_buy = 2131296328;
			
			// aapt resource value: 0x7f0900e4
			public const int bt_change = 2131296484;
			
			// aapt resource value: 0x7f0900e3
			public const int bt_delete = 2131296483;
			
			// aapt resource value: 0x7f090039
			public const int bt_gacha = 2131296313;
			
			// aapt resource value: 0x7f09000c
			public const int bt_id_card = 2131296268;
			
			// aapt resource value: 0x7f09001a
			public const int bt_item = 2131296282;
			
			// aapt resource value: 0x7f090056
			public const int bt_lode_game = 2131296342;
			
			// aapt resource value: 0x7f09001f
			public const int bt_magic = 2131296287;
			
			// aapt resource value: 0x7f090055
			public const int bt_new_game = 2131296341;
			
			// aapt resource value: 0x7f0900a9
			public const int bt_next = 2131296425;
			
			// aapt resource value: 0x7f09001d
			public const int bt_normal = 2131296285;
			
			// aapt resource value: 0x7f090057
			public const int bt_quite_game = 2131296343;
			
			// aapt resource value: 0x7f09001b
			public const int bt_runaway = 2131296283;
			
			// aapt resource value: 0x7f090049
			public const int bt_sell = 2131296329;
			
			// aapt resource value: 0x7f09001e
			public const int bt_skill = 2131296286;
			
			// aapt resource value: 0x7f09002f
			public const int bt_skill_List = 2131296303;
			
			// aapt resource value: 0x7f090052
			public const int bt_start = 2131296338;
			
			// aapt resource value: 0x7f09000e
			public const int bt_tab_e = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int bt_tab_j = 2131296269;
			
			// aapt resource value: 0x7f090091
			public const int cancel_action = 2131296401;
			
			// aapt resource value: 0x7f090099
			public const int chronometer = 2131296409;
			
			// aapt resource value: 0x7f0900e9
			public const int content = 2131296489;
			
			// aapt resource value: 0x7f090087
			public const int content_container = 2131296391;
			
			// aapt resource value: 0x7f0900e2
			public const int dv_item = 2131296482;
			
			// aapt resource value: 0x7f0900a0
			public const int end_padder = 2131296416;
			
			// aapt resource value: 0x7f090051
			public const int et_account = 2131296337;
			
			// aapt resource value: 0x7f0900a8
			public const int et_input = 2131296424;
			
			// aapt resource value: 0x7f090070
			public const int et_search = 2131296368;
			
			// aapt resource value: 0x7f090036
			public const int fl_father = 2131296310;
			
			// aapt resource value: 0x7f09004b
			public const int fl_fragment = 2131296331;
			
			// aapt resource value: 0x7f090059
			public const int fl_step_one = 2131296345;
			
			// aapt resource value: 0x7f090008
			public const int forever = 2131296264;
			
			// aapt resource value: 0x7f0900e1
			public const int gl_view = 2131296481;
			
			// aapt resource value: 0x7f090071
			public const int gv_grid = 2131296369;
			
			// aapt resource value: 0x7f09009b
			public const int icon = 2131296411;
			
			// aapt resource value: 0x7f09009f
			public const int icon_group = 2131296415;
			
			// aapt resource value: 0x7f0900b9
			public const int ijk_iv_rotation = 2131296441;
			
			// aapt resource value: 0x7f09009a
			public const int info = 2131296410;
			
			// aapt resource value: 0x7f090009
			public const int italic = 2131296265;
			
			// aapt resource value: 0x7f090000
			public const int item_touch_helper_previous_elevation = 2131296256;
			
			// aapt resource value: 0x7f090024
			public const int iv_back = 2131296292;
			
			// aapt resource value: 0x7f090031
			public const int iv_background = 2131296305;
			
			// aapt resource value: 0x7f09005f
			public const int iv_banana = 2131296351;
			
			// aapt resource value: 0x7f090012
			public const int iv_battle_info = 2131296274;
			
			// aapt resource value: 0x7f09005c
			public const int iv_bg = 2131296348;
			
			// aapt resource value: 0x7f090030
			public const int iv_char_body = 2131296304;
			
			// aapt resource value: 0x7f090038
			public const int iv_character = 2131296312;
			
			// aapt resource value: 0x7f090020
			public const int iv_character_avatar = 2131296288;
			
			// aapt resource value: 0x7f090083
			public const int iv_delete = 2131296387;
			
			// aapt resource value: 0x7f090054
			public const int iv_film_into = 2131296340;
			
			// aapt resource value: 0x7f090065
			public const int iv_full_screen = 2131296357;
			
			// aapt resource value: 0x7f090074
			public const int iv_img = 2131296372;
			
			// aapt resource value: 0x7f0900e5
			public const int iv_item = 2131296485;
			
			// aapt resource value: 0x7f090043
			public const int iv_menu_attack = 2131296323;
			
			// aapt resource value: 0x7f090045
			public const int iv_menu_character = 2131296325;
			
			// aapt resource value: 0x7f090044
			public const int iv_menu_lottery = 2131296324;
			
			// aapt resource value: 0x7f090047
			public const int iv_menu_room = 2131296327;
			
			// aapt resource value: 0x7f090046
			public const int iv_menu_shop = 2131296326;
			
			// aapt resource value: 0x7f090013
			public const int iv_monster_pic = 2131296275;
			
			// aapt resource value: 0x7f09006f
			public const int iv_non = 2131296367;
			
			// aapt resource value: 0x7f090064
			public const int iv_play = 2131296356;
			
			// aapt resource value: 0x7f090077
			public const int iv_tabicon = 2131296375;
			
			// aapt resource value: 0x7f0900cf
			public const int iv_trumb = 2131296463;
			
			// aapt resource value: 0x7f090062
			public const int iv_wait = 2131296354;
			
			// aapt resource value: 0x7f090040
			public const int iv_weather = 2131296320;
			
			// aapt resource value: 0x7f09005d
			public const int iv_winter = 2131296349;
			
			// aapt resource value: 0x7f09005e
			public const int iv_yuri = 2131296350;
			
			// aapt resource value: 0x7f090001
			public const int line1 = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int line3 = 2131296258;
			
			// aapt resource value: 0x7f09001c
			public const int ll_attack_menu = 2131296284;
			
			// aapt resource value: 0x7f090015
			public const int ll_battle_info = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int ll_battle_menu = 2131296278;
			
			// aapt resource value: 0x7f0900ce
			public const int ll_bg = 2131296462;
			
			// aapt resource value: 0x7f0900ac
			public const int ll_bottom_bar = 2131296428;
			
			// aapt resource value: 0x7f09002b
			public const int ll_clothes = 2131296299;
			
			// aapt resource value: 0x7f090068
			public const int ll_error = 2131296360;
			
			// aapt resource value: 0x7f090050
			public const int ll_input = 2131296336;
			
			// aapt resource value: 0x7f090018
			public const int ll_main_menu = 2131296280;
			
			// aapt resource value: 0x7f090042
			public const int ll_menu = 2131296322;
			
			// aapt resource value: 0x7f0900a1
			public const int ll_non = 2131296417;
			
			// aapt resource value: 0x7f09002d
			public const int ll_ornament = 2131296301;
			
			// aapt resource value: 0x7f090076
			public const int ll_tabback = 2131296374;
			
			// aapt resource value: 0x7f0900e8
			public const int ll_title = 2131296488;
			
			// aapt resource value: 0x7f090029
			public const int ll_weapon = 2131296297;
			
			// aapt resource value: 0x7f09008c
			public const int loAlertButtons = 2131296396;
			
			// aapt resource value: 0x7f09007a
			public const int loAlertHeader = 2131296378;
			
			// aapt resource value: 0x7f0900aa
			public const int lv_chose_equip = 2131296426;
			
			// aapt resource value: 0x7f090053
			public const int lv_history = 2131296339;
			
			// aapt resource value: 0x7f090079
			public const int lv_list = 2131296377;
			
			// aapt resource value: 0x7f090017
			public const int lv_skill_or_item = 2131296279;
			
			// aapt resource value: 0x7f0900a4
			public const int lv_skills = 2131296420;
			
			// aapt resource value: 0x7f090093
			public const int media_actions = 2131296403;
			
			// aapt resource value: 0x7f0900ea
			public const int message = 2131296490;
			
			// aapt resource value: 0x7f0900ec
			public const int negativeButton = 2131296492;
			
			// aapt resource value: 0x7f09000a
			public const int normal = 2131296266;
			
			// aapt resource value: 0x7f09009d
			public const int notification_background = 2131296413;
			
			// aapt resource value: 0x7f090096
			public const int notification_main_column = 2131296406;
			
			// aapt resource value: 0x7f090095
			public const int notification_main_column_container = 2131296405;
			
			// aapt resource value: 0x7f0900c7
			public const int operation_bg = 2131296455;
			
			// aapt resource value: 0x7f090086
			public const int outmost_container = 2131296390;
			
			// aapt resource value: 0x7f090026
			public const int pb_exp = 2131296294;
			
			// aapt resource value: 0x7f090011
			public const int pb_monster_hp = 2131296273;
			
			// aapt resource value: 0x7f0900e0
			public const int play_icon = 2131296480;
			
			// aapt resource value: 0x7f0900eb
			public const int positiveButton = 2131296491;
			
			// aapt resource value: 0x7f09006e
			public const int rc_episodes = 2131296366;
			
			// aapt resource value: 0x7f09009c
			public const int right_icon = 2131296412;
			
			// aapt resource value: 0x7f090097
			public const int right_side = 2131296407;
			
			// aapt resource value: 0x7f09003c
			public const int rl_father = 2131296316;
			
			// aapt resource value: 0x7f090081
			public const int rl_health = 2131296385;
			
			// aapt resource value: 0x7f090072
			public const int rl_item = 2131296370;
			
			// aapt resource value: 0x7f090063
			public const int rl_menu = 2131296355;
			
			// aapt resource value: 0x7f09003a
			public const int rl_messageBox = 2131296314;
			
			// aapt resource value: 0x7f09003d
			public const int rl_title = 2131296317;
			
			// aapt resource value: 0x7f09005a
			public const int rl_tv_father = 2131296346;
			
			// aapt resource value: 0x7f090060
			public const int rl_video = 2131296352;
			
			// aapt resource value: 0x7f090061
			public const int rl_wait = 2131296353;
			
			// aapt resource value: 0x7f09007e
			public const int rl_weapon = 2131296382;
			
			// aapt resource value: 0x7f090067
			public const int sb_progress = 2131296359;
			
			// aapt resource value: 0x7f09004e
			public const int si_indicator = 2131296334;
			
			// aapt resource value: 0x7f0900dd
			public const int simple_player_brightness_controller = 2131296477;
			
			// aapt resource value: 0x7f0900dc
			public const int simple_player_brightness_controller_container = 2131296476;
			
			// aapt resource value: 0x7f0900de
			public const int simple_player_select_stream_container = 2131296478;
			
			// aapt resource value: 0x7f0900df
			public const int simple_player_select_streams_list = 2131296479;
			
			// aapt resource value: 0x7f0900d9
			public const int simple_player_settings_container = 2131296473;
			
			// aapt resource value: 0x7f0900bb
			public const int simple_player_stream_name = 2131296443;
			
			// aapt resource value: 0x7f0900db
			public const int simple_player_volume_controller = 2131296475;
			
			// aapt resource value: 0x7f0900da
			public const int simple_player_volume_controller_container = 2131296474;
			
			// aapt resource value: 0x7f090092
			public const int status_bar_latest_event_content = 2131296402;
			
			// aapt resource value: 0x7f090014
			public const int sv_battle_info = 2131296276;
			
			// aapt resource value: 0x7f09004c
			public const int tabhost = 2131296332;
			
			// aapt resource value: 0x7f090003
			public const int text = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int text2 = 2131296260;
			
			// aapt resource value: 0x7f090098
			public const int time = 2131296408;
			
			// aapt resource value: 0x7f090005
			public const int title = 2131296261;
			
			// aapt resource value: 0x7f09007d
			public const int tvAlert = 2131296381;
			
			// aapt resource value: 0x7f090089
			public const int tvAlertCancel = 2131296393;
			
			// aapt resource value: 0x7f09007c
			public const int tvAlertMsg = 2131296380;
			
			// aapt resource value: 0x7f09007b
			public const int tvAlertTitle = 2131296379;
			
			// aapt resource value: 0x7f090027
			public const int tv_Att = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int tv_Def = 2131296296;
			
			// aapt resource value: 0x7f090021
			public const int tv_HP = 2131296289;
			
			// aapt resource value: 0x7f0900ab
			public const int tv_Illustrate = 2131296427;
			
			// aapt resource value: 0x7f090022
			public const int tv_MP = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int tv_SP = 2131296291;
			
			// aapt resource value: 0x7f09003e
			public const int tv_ap_number = 2131296318;
			
			// aapt resource value: 0x7f09006b
			public const int tv_art = 2131296363;
			
			// aapt resource value: 0x7f09007f
			public const int tv_att = 2131296383;
			
			// aapt resource value: 0x7f090033
			public const int tv_change_background = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int tv_change_info = 2131296308;
			
			// aapt resource value: 0x7f09002c
			public const int tv_clothes = 2131296300;
			
			// aapt resource value: 0x7f09003b
			public const int tv_content = 2131296315;
			
			// aapt resource value: 0x7f0900a7
			public const int tv_cost_point = 2131296423;
			
			// aapt resource value: 0x7f090080
			public const int tv_def = 2131296384;
			
			// aapt resource value: 0x7f090041
			public const int tv_exp = 2131296321;
			
			// aapt resource value: 0x7f090084
			public const int tv_goods_name = 2131296388;
			
			// aapt resource value: 0x7f090085
			public const int tv_goods_price = 2131296389;
			
			// aapt resource value: 0x7f090082
			public const int tv_healingPoint = 2131296386;
			
			// aapt resource value: 0x7f09006c
			public const int tv_intro = 2131296364;
			
			// aapt resource value: 0x7f090073
			public const int tv_item = 2131296371;
			
			// aapt resource value: 0x7f0900e7
			public const int tv_item_maker = 2131296487;
			
			// aapt resource value: 0x7f0900e6
			public const int tv_item_name = 2131296486;
			
			// aapt resource value: 0x7f090035
			public const int tv_leave = 2131296309;
			
			// aapt resource value: 0x7f09000f
			public const int tv_level = 2131296271;
			
			// aapt resource value: 0x7f0900a3
			public const int tv_magic = 2131296419;
			
			// aapt resource value: 0x7f090037
			public const int tv_mani = 2131296311;
			
			// aapt resource value: 0x7f090010
			public const int tv_monster_name = 2131296272;
			
			// aapt resource value: 0x7f090025
			public const int tv_name = 2131296293;
			
			// aapt resource value: 0x7f09004f
			public const int tv_non = 2131296335;
			
			// aapt resource value: 0x7f09006d
			public const int tv_open_intro = 2131296365;
			
			// aapt resource value: 0x7f09002e
			public const int tv_ornament = 2131296302;
			
			// aapt resource value: 0x7f090066
			public const int tv_progress = 2131296358;
			
			// aapt resource value: 0x7f090032
			public const int tv_rest = 2131296306;
			
			// aapt resource value: 0x7f090069
			public const int tv_retry = 2131296361;
			
			// aapt resource value: 0x7f0900a2
			public const int tv_skill = 2131296418;
			
			// aapt resource value: 0x7f0900a6
			public const int tv_skill_introduce = 2131296422;
			
			// aapt resource value: 0x7f0900a5
			public const int tv_skill_name = 2131296421;
			
			// aapt resource value: 0x7f090078
			public const int tv_tabtext = 2131296376;
			
			// aapt resource value: 0x7f09006a
			public const int tv_title = 2131296362;
			
			// aapt resource value: 0x7f0900ed
			public const int tv_toast = 2131296493;
			
			// aapt resource value: 0x7f09003f
			public const int tv_total_money = 2131296319;
			
			// aapt resource value: 0x7f09005b
			public const int tv_twinkle = 2131296347;
			
			// aapt resource value: 0x7f090075
			public const int tv_up_title = 2131296373;
			
			// aapt resource value: 0x7f090058
			public const int tv_version_name = 2131296344;
			
			// aapt resource value: 0x7f09002a
			public const int tv_weapon = 2131296298;
			
			// aapt resource value: 0x7f0900cd
			public const int video_view = 2131296461;
			
			// aapt resource value: 0x7f09008a
			public const int viewStubHorizontal = 2131296394;
			
			// aapt resource value: 0x7f09008b
			public const int viewStubVertical = 2131296395;
			
			// aapt resource value: 0x7f09004d
			public const int vp_Pager = 2131296333;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0002
			public const int animation_default_duration = 2131492866;
			
			// aapt resource value: 0x7f0c0000
			public const int cancel_button_image_alpha = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int status_bar_notification_info_maxnum = 2131492865;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_ai_cart_konw = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_battle_main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_character_main_page = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_colone_room_main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int activity_gacha_main_page = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int activity_home_production = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_home_shop = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int activity_home_shop_pager = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int activity_main_continue = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int activity_main_main = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int activity_main_newgame = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int activity_prologue_main = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int activity_select_battle_map = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int film_activity_film_details = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int film_activity_film_details_ijk = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int film_activity_home_page = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int film_item_film_episode = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int film_item_film_list = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int frag_item_shop_tab = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int fragment_shop_list = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int include_alertheader = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int item_alertbutton = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int item_battle_skill_or_item = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int item_chose_soubi_item = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int item_search_history = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int item_shop_goods = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int item_simplestring = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int layout_alertview = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int layout_alertview_actionsheet = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int layout_alertview_alert = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int layout_alertview_alert_horizontal = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int layout_alertview_alert_vertical = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int notification_action = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int notification_action_tombstone = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int notification_media_action = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int notification_media_cancel_action = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int notification_template_big_media = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int notification_template_big_media_custom = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int notification_template_big_media_narrow = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int notification_template_big_media_narrow_custom = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int notification_template_custom_big = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int notification_template_icon_group = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int notification_template_lines_media = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int notification_template_media = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int notification_template_media_custom = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int notification_template_part_chronometer = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int notification_template_part_time = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int pop_character_skills = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int pop_producer_status_input = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int pop_soubi_select = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int popwin_item_illustrate = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int simple_player_controlbar = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int simple_player_list_item = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int simple_player_topbar = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int simple_player_touch_gestures = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int simple_player_view_player = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int test_activity_slid_menu = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int test_hand_v = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int test_item_slid_menu = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int utils_diy_dialog = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int utils_diy_toast = 2130968636;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int bg_battle_map = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bg_battle_monster_name = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bg_flash_screen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int bg_hp_progreesbar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int bg_room_select = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int bg_room_select_on = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int daily_chihaya_one = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int daily_haruka_one = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int defaut_bg = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int icon = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int icon_ac_video_error = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int icon_back = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int icon_battle_info = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int icon_battle_info_back = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int icon_defaut_avator = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int icon_film_back = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int icon_film_full_screen = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int icon_film_play = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int icon_film_stop = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int icon_film_thumb = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int icon_film_wait = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int icon_fuku_off = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int icon_fuku_on = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int icon_kareiseki_off = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int icon_kareiseki_on = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int icon_kasari_off = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int icon_kasari_on = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int icon_list_del = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int icon_menu_chara = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int icon_menu_fight = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int icon_menu_gacha = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int icon_menu_jishi = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int icon_menu_shop = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int icon_search = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int icon_shoppingbag = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int login_bg_banner = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int nameless_all_die = 2130903076;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f070000
			public const int bgm_main = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int se_duduru = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int se_money = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int se_shake = 2131165187;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0d0007
			public const int ApplicationName = 2131558407;
			
			// aapt resource value: 0x7f0d0006
			public const int Hello = 2131558406;
			
			// aapt resource value: 0x7f0d0001
			public const int app_name = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int can_not_play = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int giraffe_player_url_empty = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public const int not_support = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public const int small_problem = 2131558405;
			
			// aapt resource value: 0x7f0d0000
			public const int status_bar_notification_info_overflow = 2131558400;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a000c
			public const int AlertActivity_AlertStyle = 2131361804;
			
			// aapt resource value: 0x7f0a0013
			public const int AnimationFromButtom = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int AnimationFromTop = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int AnimationUpPopup = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int DialogFadeAnimation = 2131361809;
			
			// aapt resource value: 0x7f0a0015
			public const int Diy_dialog = 2131361813;
			
			// aapt resource value: 0x7f0a000d
			public const int SeekBarAppTheme = 2131361805;
			
			// aapt resource value: 0x7f0a0005
			public const int TextAppearance_Compat_Notification = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Info = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131361803;
			
			// aapt resource value: 0x7f0a0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Media = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int TextAppearance_Compat_Notification_Time = 2131361799;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int TextAppearance_Compat_Notification_Title = 2131361800;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int Theme_Main = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int Theme_PublicTheme = 2131361807;
			
			// aapt resource value: 0x7f0a0009
			public const int Widget_Compat_NotificationActionContainer = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int Widget_Compat_NotificationActionText = 2131361802;
			
			// aapt resource value: 0x7f0a0010
			public const int default_animation = 2131361808;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f060000
			public const int file_paths = 2131099648;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] GalTextView = new int[] {
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 2
			public const int GalTextView_textColor = 2;
			
			// aapt resource value: 0
			public const int GalTextView_textContent = 0;
			
			// aapt resource value: 1
			public const int GalTextView_textSize = 1;
			
			// aapt resource value: 4
			public const int GalTextView_textSpacingAdd = 4;
			
			// aapt resource value: 3
			public const int GalTextView_textSpacingMult = 3;
			
			// aapt resource value: 5
			public const int GalTextView_textXAlignment = 5;
			
			public static int[] GestureLockViewGroup = new int[] {
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007};
			
			// aapt resource value: 2
			public const int GestureLockViewGroup_color_finger_on = 2;
			
			// aapt resource value: 3
			public const int GestureLockViewGroup_color_finger_up = 3;
			
			// aapt resource value: 0
			public const int GestureLockViewGroup_color_no_finger_inner_circle = 0;
			
			// aapt resource value: 1
			public const int GestureLockViewGroup_color_no_finger_outer_circle = 1;
			
			// aapt resource value: 4
			public const int GestureLockViewGroup_count = 4;
			
			// aapt resource value: 5
			public const int GestureLockViewGroup_tryTimes = 5;
			
			public static int[] MaxHeightListView = new int[] {
					2130772008};
			
			// aapt resource value: 0
			public const int MaxHeightListView_maxHeight = 0;
			
			public static int[] PercentLayout_Layout = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
